github: atjontv # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: atjontv # Replace with a single Patreon username
custom: ['https://atvg-studios.com/donate'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

