---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: gradle:7.0-jdk8
  commands:
  - gradle build
  - gradle shadowJar

- name: lint
  image: gradle:7.0-jdk8
  commands:
  - gradle lintKotlin

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: gradle:7.0-jdk8
  commands:
  - gradle test

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: docs
  image: gradle:7.0-jdk8
  commands:
  - gradle dokka

...
