image: gradle:6.3-jdk8

stages:
  - build
  - test
  - lint

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - gradle build
    - gradle shadowJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    refs:
      - tags

docs:
  stage: build
  script:
    - gradle dokka
  artifacts:
    paths:
      - build/dokka
    expire_in: 1 week
  only:
    refs:
      - tags

test:
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - build/reports/tests/test

lint:
  stage: lint
  script:
    - gradle lintKotlin
