image: gradle:7.0-jdk8

stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: test
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  script:
    - gradle test
  artifacts:
    paths:
      - build/reports/tests/test
    reports:
      junit: build/test-results/test/**/TEST-*.xml

lint:
  stage: lint
  script:
    - gradle lintKotlin

build:
  stage: build
  script:
    - gradle build
    - gradle shadowJar
    - gradle publish
  artifacts:
    paths:
      - build/libs/*.jar

docs:
  stage: build
  script:
    - gradle dokkaHtml
  artifacts:
    paths:
      - build/dokka

pages:
  stage: deploy
  script:
    - mv _pages public
    # Move Dokka Documentation
    - mv build/dokka/html public/docs
    # Move JUnit Test results
    - mv build/reports/tests/test public/tests
    # Move JaCoCo Coverage results
    - mv build/reports/jacoco/test/html public/coverage
    # Move Jar files
    - mv build/libs/*.jar public/jars/
    - echo "<html><body><h1>Directory listing:</h1>" > public/jars/index.html
    - find public/jars/ -exec echo "<a href='{}'>{}</a><br/>" \; >> public/jars/index.html
    - echo "</body></html>" >> public/jars/index.html
  artifacts:
    paths:
      - public
